name: CD Workflow
on:
  push:
    branches:
      - CD_branch

jobs:
  deploying:
    runs-on: ubuntu-latest
    env:
        ssh_key: ${{ secrets.SSH_KEY }}
        seed: ${{ vars.SEED }}
    steps:
      - uses: actions/checkout@v3
      - name: Python run for seed from GitHub Environmental Variable
        run:
          result=$(python3 task_Morozov_Vitaly_prime_checksum.py "$seed")
          echo "result=$result" >> $GITHUB_ENV
      - name: Saving answer in env
        env:
          answer: ${{ env.result }}
      - name: Set SSH key
        run: |
          mkdir -p ~/.ssh && \
          echo "$ssh_key" | base64 -d > ~/.ssh/id_rsa && \
          chmod 0600 ~/.ssh/id_rsa
      - name: File with answer creation
        run: |
          ssh -o StrictHostKeyChecking=no bdb2c2023q4_guest_3@brain-client.bigdatateam.org <<EOF
          mkdir -p ~/vitaly_morozov97
          echo "$answer" > ~/vitaly_morozov97/task41.txt
          exit
          EOF